### ISSUE TITLE
fakechroot + debootstrap doesn't work on current distributions

### ISSUE THREAD

**Issue by p-e-w** [dex4er/fakechroot#36] opened 2015-08-12 19:33 UTC
I realize this repo looks quite dead, but since noone else has posted this issue yet here it is: The "debootstrap without root" use case doesn't actually seem to work with any recent distro anymore. I've tested Fedora, Mint and Ubuntu (all vanilla installations in VMs) by running

```
fakechroot fakeroot debootstrap sid /tmp/sid
```

as suggested in the README. In all three cases, the error

```
W: Failure trying to run: chroot /tmp/sid dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.38_amd64.deb
```

halted the bootstrapping process. Looking at `debootstrap.log` as suggested by the output revealed the following details:

### Fedora 22

```
cannot get security labeling handle: No such file or directory
```

### Mint 17.2 + Ubuntu 15.04

```
dpkg: symbol lookup error: dpkg: undefined symbol: setexecfilecon
```

<br>

Furthermore, I can confirm that the following modifications, found by a web search for similar issues, do **not** fix the problem:

* Invoking fakechroot with `--use-system-libs`
* Adding `/usr/sbin` / `/sbin` to the `PATH`
* Invoking debootstrap with `--variant=fakechroot`
* Invoking debootstrap with `--foreign` and two-staging the installation

Alas, there currently seems to be no way to actually get debootstrap to work without superuser privileges.

**Comment by sveniu** [comment] 2015-09-23 06:57
Possibly the same issue on Debian Jessie, to debootstrap Debian Jessie or Wheezy, ref [Debian bug 745082](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=745082).

**Comment by gophercg** [comment] 2015-09-24 01:58
Similar error occurs on a Ubuntu 14.04. But before running the debootstrap command, debootstrap must be extracted/setup, and dialog installed inside the fakechroot context, to remove various errors.

debootstrap.log:
```
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
Selecting previously unselected package base-passwd.
(Reading database ... 0 files and directories currently installed.)
Preparing to unpack .../base-passwd_3.5.38_amd64.deb ...
dpkg: symbol lookup error: dpkg: undefined symbol: setexecfilecon
dpkg: error processing archive /var/cache/apt/archives/base-passwd_3.5.38_amd64.deb (--install):
 subprocess new pre-installation script returned error exit status 127
dpkg: symbol lookup error: dpkg: undefined symbol: setexecfilecon
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 127
Errors were encountered while processing:
 /var/cache/apt/archives/base-passwd_3.5.38_amd64.deb
```

**Comment by sveniu** [comment] 2015-10-06 06:20
The Debian and Ubuntu issue that stems from issues with libaudit called from libpam, is addressed in #37. I'm hoping to get it pulled into master, but looking at the repository log, it might be a challenge.

**Closed** 2015-10-26 17:46 UTC

**Comment by ProgVal** [comment] 2016-08-25 19:15
The patch in #37 (and also the patch in Debian) do not fix the second issue, I get the same error as @gophercg, on 14.04.4.

**Comment by ProgVal** [comment] 2016-08-25 19:19
Actually, Ubuntu 14.04.4 is the host, and Debian 8 is the chrooted OS. So I'm not sure which one is the cause.
